swagger: '2.0'
info:
  title: StoryTechnologies Story API
  version: '0.1'
consumes:
  - application/json
produces:
  - application/json
basePath: /1.0
paths:
  '/topics':
    get:
      operationId: engine.api.service.get_topics
      summary: Get a collection of topics
      parameters:
          - $ref: '#/parameters/instance_of'
          - $ref: '#/parameters/offset'
          - $ref: '#/parameters/limit'
      responses:
        200:
          description: Return collection of topics
        404:
          description: No topics exist
  '/topics/{identifier}':
    get:
      operationId: engine.api.service.get_topic
      summary: Get a single topic
      parameters:
        - $ref: '#/parameters/identifier'
      responses:
        200:
          description: Return topic
        404:
          description: Topic does not exist
  '/scenes/{identifier}':
    get:
      operationId: engine.api.service.get_scene
      summary: Get a single scene
      parameters:
        - $ref: '#/parameters/identifier'
      responses:
        200:
          description: Return scene
        404:
          description: Scene does not exist
  '/props/{identifier}':
    get:
      operationId: engine.api.service.get_prop
      summary: Get a single prop
      parameters:
        - $ref: '#/parameters/identifier'
      responses:
        200:
          description: Return prop
        404:
          description: Prop does not exist
  '/characters/{identifier}':
    get:
      operationId: engine.api.service.get_character
      summary: Get a single character
      parameters:
        - $ref: '#/parameters/identifier'
      responses:
        200:
          description: Return character
        404:
          description: Character does not exist

parameters:
  identifier:
    name: identifier
    description: Unique identifier
    in: path
    type: string
    required: true
    pattern: "^\\*|[a-zA-Z0-9-]+$"
  instance_of:
    name: instance_of
    description: Unique 'instance of' identifier
    in: query
    type: string
    required: false
    pattern: "^\\*|[a-zA-Z0-9-]+$"
  offset:
    name: offset
    description: Positive number
    in: query
    type: number
    required: false
    pattern: "^[0-9]+$"
  limit:
    name: limit
    description: Positive number
    in: query
    type: number
    required: false
    pattern: "^[0-9]+$"
